### ISSUE TITLE
Support for mathics3？

### ISSUE THREAD

**Issue by horizonl** [mathics/IMathics#15]

**Comment by rocky** [comment]
My own personal take is that there we are working through massive reorganization on the core side and there https://github.com/Mathics3/iwolfram is on the horizon.

But all of this is open-source so anybody can work on anything. Hey, how about you?

**Comment by horizonl** [comment]
> My own personal take is that there we are working through massive reorganization on the core side and there https://github.com/Mathics3/iwolfram is on the horizon.
> 
> But all of this is open-source so anybody can work on anything. Hey, how about you?

Thanks for your suggestion. I've tried [iwolfram](https://github.com/Mathics3/iwolfram), but the kernel always dead. And I tried to modified the code in it, but my code skill is so poor that I did not make it work.

**Comment by rocky** [comment]
I can understand your position. I often feel that way myself as I work on the code. 

No one is born understanding code, let alone complex code. It is a matter though of trying and keeping at it. And when you have questions, asking.

**Comment by mmatera** [comment]
IWolfram was written in order to work with the Wolfram Kernel. I made some efforts to make it works with Mathics, but as the interface of Mathics was changing, it gets broken.
@horizonl, if you have time and the will, I can help you in following and fixing the code. I plan to do that, but currently, I am investing most of my free time fixing Mathics in order to have a stable interface.

**Comment by horizonl** [comment]
> IWolfram was written in order to work with the Wolfram Kernel. I made some efforts to make it works with Mathics, but as the interface of Mathics was changing, it gets broken.
> @horizonl, if you have time and the will, I can help you in following and fixing the code. I plan to do that, but currently, I am investing most of my free time fixing Mathics in order to have a stable interface.

thank you for your kindness and code. I will try to make my contributions.
